name: billing_app_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  mailer: ^6.4.1
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.4
  file_picker: ^9.2.1
#  encrypt: ^5.0.3
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_charts: ^0.5.2
  crypto: ^3.0.6
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  table_calendar: ^3.2.0
  open_file: ^3.5.10
  flutter_pdfview: ^1.4.0+1
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.3.0
  retry: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  animate_do: ^4.2.0
  webview_flutter: ^4.13.0
  uuid: ^4.5.1
  razorpay_flutter: ^1.4.0
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.2
  flutter_barcode_scanner: ^2.0.0
  window_manager: ^0.5.0
  menu_bar: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  objectbox_generator: ^4.3.0
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.0
  msix: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

msix_config:
  display_name: Codweb Billing App  # Must be a string
  publisher_display_name: Codweb Software  # Must be a string
  identity_name: com.codweb.app  # Must be a string
  msix_version: 1.0.0.0
  certificate_path: C:/Users/Shrik/cert.pfx
  certificate_password: namdevmaharaj
  install_location: "$env:ProgramFiles\\codweb"